# Generated by Django 5.1.2 on 2024-10-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_rename_licence_no_driver_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
