# Generated by Django 5.1.2 on 2024-10-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_current_location_driver_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='driver.driver'),
            preserve_default=False,
        ),
    ]
